/*
 * flags.h
 *
 *  Created on: 16 sept. 2020
 *      Author: Theo
 */

#ifndef EVENTS_FLAGS_H_
#define EVENTS_FLAGS_H_

typedef enum Flags_e{
	//Flags


	//GYRO
	FLAG_GYRO_OK,
	FLAG_GYRO_READING,
	FLAG_GYRO_DATA_READY,
	FLAG_GYRO_FILTERED_DATA_READY,


	//ACC
	FLAG_ACC_OK,
	FLAG_ACC_READING,
	FLAG_ACC_DATA_READY,
	FLAG_ACC_FILTERED_DATA_READY,

	//Barometer
	FLAG_BARO_OK,
	FLAG_BARO_TEMP_RAW_RDY,
	FLAG_BARO_PRESSURE_RAW_RDY,
	FLAG_BARO_PRESSURE_RDY,
	FLAG_BARO_ALTITUDE_RDY,

	//RADIO
	FLAG_IBUS_DATA_RDY,

	//Channel analysis
	FLAG_CHAN_5_POS_1,
	FLAG_CHAN_5_POS_3,

	FLAG_CHAN_6_POS_1,
	FLAG_CHAN_6_POS_2,
	FLAG_CHAN_6_POS_3,

	FLAG_CHAN_7_POS_1,
	FLAG_CHAN_7_POS_2,
	FLAG_CHAN_7_POS_3,

	FLAG_CHAN_8_POS_1,
	FLAG_CHAN_8_POS_3,

	FLAG_CHAN_9_PUSH,

	FLAG_CHAN_10_ON,

	FLAG_THROTTLE_HIGH,
	FLAG_THROTTLE_LOW,
	FLAG_THROTTLE_NULL,

	//Overall drone's state description
	FLAG_ARMING,
	FLAG_ARMED,
	FLAG_BUSY, 		//ex: calibrating gyro => no take off etc
	FLAG_GYRO_CALI_IN_PROGRESS,
	FLAG_GYRO_CALI_DONE,
	FLAG_FLYING,
	FLAG_MANUAL,

	FLAG_COUNT
}Flags_e;


#endif /* EVENTS_FLAGS_H_ */
