/*
 * mask_def_enum.h
 *
 *  Created on: 4 oct. 2020
 *      Author: Th�o
 */

#ifndef EVENTS_MASK_DEF_ENUM_H_
#define EVENTS_MASK_DEF_ENUM_H_

typedef enum{
	//MASK_DEF

	//Gyro
	MASK_GYRO_INIT_OK = 0,
	MASK_GYRO_INIT_COUNT,

	MASK_GYRO_DATA_READY = 0,
	MASK_GYRO_DATA_READY_COUNT,

	//Acc
	MASK_ACC_INIT_OK = 0,
	MASK_ACC_INIT_COUNT,

	MASK_ACC_DATA_READY = 0,
	MASK_ACC_DATA_READY_COUNT,

	//Orientation
	MASK_ORIENTATION_UPDATE = 0,
	MASK_ORIENTATION_UPDATE_COUNT,

	//Ibus
	MASK_IBUS_DATA_RDY = 0,
	MASK_IBUS_DATA_RDY_COUNT,

	//On the ground
	MASK_ON_THE_GROUND_FLYING = 0,
	MASK_ON_THE_GROUND_ARMING,
	MASK_ON_THE_GROUND_CALIBRATION,
	MASK_ON_THE_GROUND_COUNT,

	//Manual accro
	MASK_MANUAL_ACCRO_ON_THE_GROUND = 0,
	MASK_MANUAL_ACCRO_COUNT,

	//Manual angle
	MASK_MANUAL_ANGLE_ON_THE_GROUND = 0,
	MASK_MANUAL_ANGLE_COUNT,

	//Manual angle alti auto
	MASK_MANUAL_ANGLE_ALTI_AUTO = 0,
	MASK_MANUAL_ANGLE_ALTI_AUTO_COUNT,

	//Gyro acc calibration
	MASK_GYRO_ACC_CALIBRATION = 0,
	MASK_GYRO_ACC_COUNT,

	//Baro data ready
	MASK_BARO_DATA_READY_TEMP_RAW = 0,
	MASK_BARO_DATA_READY_PRESSURE_RAW,
	MASK_BARO_DATA_READY_PRESSURE,
	MASK_BARO_DATA_READY_COUNT,

	//Arming
	MASK_ARMING_ON_THE_GROUND = 0,
	MASK_ARMING_COUNT,

	MASK_DEF_LAST
}mask_def_ids_t;

#endif /* EVENTS_MASK_DEF_ENUM_H_ */
